#!/bin/bash

Help()
{
   # Display Help
   echo "This script will run the most recent build of a program in the given language for a given year and day."
   echo
   echo "languages: go | cpp | zig" 
   echo
   echo "./run go 2024 24"
   echo "This runs the program for the 24th day of 2024 in go"
   echo
   echo "Subject to whatever languages I've decided to write the program in for any given day"
   echo "It most likely will be go"
   echo "Rebuild the project using the `build` command"
}

if [ "${1}" == "" ] || [ "${2}" == "" ] || [ "${3}" == "" ] || [ "${1}" == "-h" ]; then
	Help
	exit
fi

if [ ${1} == "go" ] || [ ${1} == "cpp" ] || [ ${1} == "zig" ]; then
	."/bin/${1}_${2}_${3}"
else
	echo "I don't know how to run ${1}, brother. You are vibing too hard :'("
	exit
fi


