#!/bin/bash

Help()
{
   # Display Help
   echo "This script will run the program in the given language for a given year and day."
   echo
   echo "languages: go | cpp" 
   echo
   echo "./run go 2024 24"
   echo "This runs the program for the 24th day of 2024 in go"
   echo
   echo "Subject to whatever languages I've decided to write the program in for any given day"
   echo "It most likely will be go"
}

if [ "${1}" == "" ] || [ "${2}" == "" ] || [ "${3}" == "" ] || [ "${1}" == "-h" ]; then
	Help
	exit
fi

if [ ${1} == "go" ]; then
	file="internal/${2}/day${3}/main.go"
	alt="internal/${2}/day${3}/go/main.go"

	if [ -f $file ]; then
		go run $file

	elif [ -f $alt ]; then
		go run $alt

	else 
		echo "I couldn't find the main file, brother..."
	fi

elif [ ${1} == "cpp" ]; then
	file="internal/${2}/day${3}/cpp/main.cpp"
	alt="internal/${2}/day${3}/main.cpp"

	if [ -f $file ]; then
		g++ -o "bin/${2}_${3}" $file
		."/bin/${2}_${3}"

	elif [ -f $alt ]; then
		g++ -o "bin/${2}_${3}" $alt
		."/bin/${2}_${3}"

	else 
		echo "I couldn't find the main file, brother..."
	fi
else
	echo "I don't know how to run ${1}, brother. You are vibing too hard :'("
	exit
fi


